### API tests

POST http://localhost:4000/posts
Content-Type: application/json

{
    "content": "This is the content of my first post.",
    "sender": "Alice"
}



GET http://localhost:4000/posts


GET http://localhost:4000/posts?sender=Alice


GET http://localhost:4000/posts/693df77ca79d1de50c7f4b2a


PUT http://localhost:4000/posts/693df77ca79d1de50c7f4b2a
Content-Type: application/json

{
    "content": "This is another updated content of my first post."
}
